# Generated by Django 2.2 on 2019-05-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointsEau', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointeau',
            name='nom',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
