# Generated by Django 2.2.1 on 2019-05-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointsEau', '0003_pointeau_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointeau',
            name='description',
        ),
    ]
