# Generated by Django 2.2.1 on 2019-05-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointsEau', '0004_remove_pointeau_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointeau',
            name='desc',
            field=models.CharField(default='Description', max_length=255),
        ),
    ]
